/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class cadastrocliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(cadastrocliente.class.getName());

    /**
     * Creates new form cadastrocliente
     */
    public cadastrocliente() {
        initComponents();
    }
    
    private Boolean validacoes(){
        if (jTextFieldNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo nome deve ser preenchido");
                    jTextFieldNome.requestFocus();
                    return false;
        }
        
        if (jTextFieldCPF.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo cpf deve ser preenchido");
            jTextFieldCPF.requestFocus();
            return false;
        }
        
        if (!jRadioButtonMasculino.isSelected() && !jRaddioButtonFeminino.isSelected()){
            JOptionPane.showMessageDialog(null, "Opção de gênero não informada");
            return false;
        }
        
        if (!jCheckBoxTermos.isSelected()){
            JOptionPane.showMessageDialog(null, "Os termos de uilização do sistemas não foram aceitos");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGenero = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelCPF = new javax.swing.JLabel();
        jTextFieldCPF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxCidade = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonFeminino = new javax.swing.JRadioButton();
        jRadioButtonMasculino = new javax.swing.JRadioButton();
        jCheckBoxTermos = new javax.swing.JCheckBox();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Cadastro do Cliente");

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNome.setText("Nome");

        jTextFieldNome.addActionListener(this::jTextFieldNomeActionPerformed);

        jLabelCPF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCPF.setText("CPF");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Cidade");

        jComboBoxCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Abaetetuba", "Abreu e Lima", "Açailândia", "Alagoinhas", "Alvorada", "Americana", "Amparo", "Anápolis", "Ananindeua", "Andradina", "Angra dos Reis", "Apucarana", "Aracaju", "Araçatuba", "Araraquara", "Araras", "Araruama", "Araucária", "Araxá", "Ariquemes", "Armação dos Búzios", "Arraial do Cabo", "Assis", "Atibaia", "Avaré", "Bagé", "Balneário Camboriú", "Barbacena", "Barcarena", "Barra do Garças", "Barra Mansa", "Barreiras", "Barretos", "Barueri", "Bauru", "Belém", "Belford Roxo", "Belo Horizonte", "Bento Gonçalves", "Betim", "Birigui", "Blumenau", "Boa Vista", "Boca do Acre", "Bofete", "Bom Jesus da Lapa", "Botucatu", "Bragança Paulista", "Brasília", "Brumado", "Brusque", "Bujari", "Cabo de Santo Agostinho", "Cabo Frio", "Caçador", "Cáceres", "Cachoeirinha", "Cachoeiro de Itapemirim", "Caetité", "Caicó", "Cajamar", "Cajazeiras", "Caldas Novas", "Camaçari", "Cametá", "Campina Grande", "Campinas", "Campo Grande", "Campo Mourão", "Campos dos Goytacazes", "Canoas", "Capão da Canoa", "Caraguatatuba", "Carapicuíba", "Caruaru", "Cascavel", "Castanhal", "Catanduva", "Caxias", "Caxias do Sul", "Chapecó", "Cianorte", "Cícero Dantas", "Cidade Ocidental", "Coari", "Codó", "Colatina", "Colombo", "Colorado do Oeste", "Conchal", "Concórdia", "Congonhas", "Conselheiro Lafaiete", "Contagem", "Corumbá", "Cosmópolis", "Cotia", "Crateús", "Crato", "Criciúma", "Cruzeiro do Sul", "Cuiabá", "Curitiba", "Curvelo", "Diadema", "Diamantina", "Divinópolis", "Dois Vizinhos", "Dourados", "Duque de Caxias", "Elias Fausto", "Embu das Artes", "Epitaciolândia", "Erechim", "Eunápolis", "Eusébio", "Feira de Santana", "Fernandópolis", "Floriano", "Florianópolis", "Formosa", "Fortaleza", "Foz do Iguaçu", "Franca", "Francisco Beltrão", "Franco da Rocha", "Garanhuns", "Garça", "Gaspar", "Gavião Peixoto", "Goiânia", "Goiana", "Governador Valadares", "Gramado", "Gravataí", "Guaçuí", "Guaíra", "Guanambi", "Guaporé", "Guará", "Guarabira", "Guarapari", "Guarapuava", "Guaratinguetá", "Guatambu", "Guaratuba", "Guarulhos", "Gurupi", "Herval d'Oeste", "Horizontina", "Hortolândia", "Ibiúna", "Igarassu", "Igarapava", "Iguatu", "Ijuí", "Ilhéus", "Imperatriz", "Indaiatuba", "Ipatinga", "Irecê", "Itabira", "Itabuna", "Itacoatiara", "Itaguaí", "Itajaí", "Itajubá", "Itamaraju", "Itanhaém", "Itapeva", "Itapevi", "Itapipoca", "Itápolis", "Itaquaquecetuba", "Itatiba", "Itaúna", "Itu", "Ituiutaba", "Itumbiara", "Ituverava", "Jaboatão dos Guararapes", "Jacareí", "Jacobina", "Jales", "Jandira", "Jaraguá do Sul", "Jaru", "Jaú", "Jequeé", "Ji-Paraná", "João Monlevade", "João Pessoa", "Joinville", "Juazeiro", "Juazeiro do Norte", "Juiz de Fora", "Jundiaí", "Lages", "Lagarto", "Lagoa Santa", "Lauro de Freitas", "Lavras", "Leme", "Limeira", "Limoeiro do Norte", "Lins", "Linhares", "Lisboa (não, essa é em Portugal) -> Lomba Grande", "Londrina", "Lorena", "Lucas do Rio Verde", "Luís Eduardo Magalhães", "Macaé", "Macapá", "Maceió", "Machadinho d'Oeste", "Madre de Deus", "Mairiporã", "Manaus", "Manhuaçu", "Marabá", "Maracanáu", "Marataízes", "Maricá", "Marília", "Maringá", "Matão", "Mauá", "Mirandópolis", "Mirassol", "Mococa", "Mogi das Cruzes", "Mogi Guaçu", "Mogi Mirim", "Monte Alto", "Montes Claros", "Mossoró", "Muriaé", "Natal", "Navegantes", "Niterói", "Nova Friburgo", "Nova Iguaçu", "Nova Lima", "Nova Mutum", "Novo Hamburgo", "Olinda", "Olímpia", "Orlândia", "Osasco", "Ourinhos", "Ouro Preto", "Palhoça", "Palmas", "Palmeira dos Índios", "Pará de Minas", "Paracatu", "Paragominas", "Paraguiçu", "Paranaguá", "Paranavaí", "Paraty", "Parnaíba", "Passo Fundo", "Passos", "Pato Branco", "Patos", "Patos de Minas", "Paulínia", "Paulista", "Pedreira", "Pelotas", "Penápolis", "Penedo", "Peruíbe", "Petrolina", "Petrópolis", "Pica-pau", "Picos", "Pindamonhangaba", "Pinhais", "Piracicaba", "Pirassununga", "Piraquara", "Poá", "Poços de Caldas", "Ponta Grossa", "Ponta Porã", "Ponte Nova", "Porto Alegre", "Porto Ferreira", "Porto Seguro", "Porto Velho", "Pouso Alegre", "Praia Grande", "Presidente Prudente", "Primavera do Leste", "Quixadá", "Recife", "Registro", "Resende", "Ribeirão Pires", "Ribeirão Preto", "Rio Branco", "Rio Claro", "Rio de Janeiro", "Rio Grande", "Rio Verde", "Rolândia", "Rondonópolis", "Sabará", "Salto", "Salvador", "Santa Bárbara d'Oeste", "Santa Cruz do Sul", "Santa Maria", "Santana", "Santana de Parnaíba", "Santarém", "Santo André", "Santo Ângelo", "Santo Antônio de Jesus", "Santos", "São Bernardo do Campo", "São Borja", "São Carlos", "São Gabriel da Cachoeira", "São Gonçalo", "São João da Boa Vista", "São João del-Rei", "São João de Meriti", "São José", "São José do Rio Preto", "São José dos Campos", "São José dos Pinhais", "São Leopoldo", "São Léo", "São Luís", "São Mateus", "São Roque", "São Sebastião", "São Vicente", "Sapucaia do Sul", "Saquarema", "Senador Canedo", "Serra", "Serra Talhada", "Sertãozinho", "Sete Lagoas", "Sinop", "Sobral", "Sorocaba", "Sumaré", "Suzano", "Taboão da Serra", "Tangará da Serra", "Taubaté", "Teixeira de Freitas", "Teófilo Otoni", "Teresina", "Teresópolis", "Três Lagoas", "Três Corações", "Trindade", "Tubaráo", "Tupã", "Uberaba", "Uberlândia", "Ubatuba", "Uruguaiana", "Valinhos", "Valparaíso de Goiás", "Varginha", "Varzea Grande", "Varzea Paulista", "Vassouras", "Viamão", "Viçosa", "Vila Velha", "Vilhena", "Vinhedo", "Vitória", "Vitória da Conquista", "Vitória de Santo Antão", "Votorantim", "Votuporanga", "Xanxerê", "Xique-Xique", "Zé Doca" }));
        jComboBoxCidade.addActionListener(this::jComboBoxCidadeActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Gênero");

        buttonGroupGenero.add(jRadioButtonFeminino);
        jRadioButtonFeminino.setText("Feminino");

        buttonGroupGenero.add(jRadioButtonMasculino);
        jRadioButtonMasculino.setText("Masculino");

        jCheckBoxTermos.setText("Aceito os termos de utilização do sistema");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(this::jButtonSalvarActionPerformed);

        jButtonCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNome))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabelCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jTextFieldCPF))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 44, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jRadioButtonMasculino)
                                .addGap(8, 8, 8)
                                .addComponent(jRadioButtonFeminino))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonSalvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonCancelar))
                                    .addComponent(jCheckBoxTermos))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCPF)
                    .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonFeminino)
                    .addComponent(jRadioButtonMasculino))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxTermos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
       
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jComboBoxCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCidadeActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (!validacoes()){
            return;
        }
        
        JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso");
        
        System.exit(0);
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new cadastrocliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupGenero;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JCheckBox jCheckBoxTermos;
    private javax.swing.JComboBox<String> jComboBoxCidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JRadioButton jRadioButtonFeminino;
    private javax.swing.JRadioButton jRadioButtonMasculino;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
